"""HW Tables var2

Revision ID: 9780acd8c7ba
Revises: a68969dfe821
Create Date: 2023-04-02 18:51:52.014266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9780acd8c7ba'
down_revision = 'a68969dfe821'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.drop_column('teachers', 'fullname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('fullname', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('teachers', 'first_name')
    # ### end Alembic commands ###
