"""HW Tables var2

Revision ID: a68969dfe821
Revises: 89abbc759c55
Create Date: 2023-04-02 18:50:34.710966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a68969dfe821'
down_revision = '89abbc759c55'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teachers_to_students')
    op.add_column('students', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'students', 'students', ['group_id'], ['id'])
    op.drop_column('students', 'email')
    op.drop_column('students', 'phone')
    op.drop_column('students', 'address')
    op.add_column('teachers', sa.Column('fullname', sa.String(length=100), nullable=True))
    op.drop_column('teachers', 'first_name')
    op.drop_column('teachers', 'email')
    op.drop_column('teachers', 'address')
    op.drop_column('teachers', 'start_work')
    op.drop_column('teachers', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('phone', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('teachers', sa.Column('start_work', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('teachers', sa.Column('address', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('teachers', sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('teachers', sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('teachers', 'fullname')
    op.add_column('students', sa.Column('address', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('phone', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'group_id')
    op.create_table('teachers_to_students',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='teachers_to_students_student_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], name='teachers_to_students_teacher_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='teachers_to_students_pkey')
    )
    # ### end Alembic commands ###
