"""Init

Revision ID: eb78858a6074
Revises: 
Create Date: 2023-04-02 18:06:15.408972

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'eb78858a6074'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('first_name', sa.String(length=100), nullable=True),
                    sa.Column('last_name', sa.String(length=100), nullable=True),
                    sa.Column('email', sa.String(length=100), nullable=True),
                    sa.Column('phone', sa.String(length=100), nullable=True),
                    sa.Column('address', sa.String(length=150), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('teachers',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('first_name', sa.String(length=100), nullable=True),
                    sa.Column('last_name', sa.String(length=100), nullable=True),
                    sa.Column('email', sa.String(length=100), nullable=True),
                    sa.Column('phone', sa.String(length=100), nullable=True),
                    sa.Column('address', sa.String(length=150), nullable=True),
                    sa.Column('start_work', sa.Date(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('teachers_to_students',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('teacher_id', sa.Integer(), nullable=True),
                    sa.Column('student_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teachers_to_students')
    op.drop_table('teachers')
    op.drop_table('students')
    # ### end Alembic commands ###
